
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author escob
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        jbtconvertidos.setFocusPainted(false);
        jbtnbienbenida.setFocusPainted(false);
        jbtnsalida.setFocusPainted(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtconvertidos = new javax.swing.JButton();
        jbtnbienbenida = new javax.swing.JButton();
        jbtnsalida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtconvertidos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtconvertidos.setText("Convertidor");
        jbtconvertidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtconvertidosActionPerformed(evt);
            }
        });

        jbtnbienbenida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnbienbenida.setText("Bienbenida");
        jbtnbienbenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbienbenidaActionPerformed(evt);
            }
        });

        jbtnsalida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnsalida.setText("Salir");
        jbtnsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsalidaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        jLabel1.setText("Menu Principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbtconvertidos)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(134, 134, 134)
                            .addComponent(jbtnbienbenida)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jbtnsalida)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jbtconvertidos)
                .addGap(18, 18, 18)
                .addComponent(jbtnbienbenida)
                .addGap(18, 18, 18)
                .addComponent(jbtnsalida)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtconvertidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtconvertidosActionPerformed
        // TODO add your handling code here:
        String dato = JOptionPane.showInputDialog("ingrese metros:");
        double metros = Double.parseDouble(dato);
        double kilometros = metros / 1000;
        double millas = metros * 0.000621;
        double centimetros = metros * 100;
        double pies = metros * 3.28;
                JOptionPane.showMessageDialog(null,
                        "kilometros "+kilometros+ 
                                
                                
                                "millas "+millas+ 
                                
                                "centimetros "+centimetros+ 
                                
                                "pies "+pies);
            
       
    
                
    }//GEN-LAST:event_jbtconvertidosActionPerformed

    private void jbtnbienbenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbienbenidaActionPerformed
        // TODO add your handling code here:
        String nombre;
        nombre = JOptionPane.showInputDialog("ingrese su nombre:");
        JOptionPane.showMessageDialog(null,"bienbenido "+nombre);
        
    }//GEN-LAST:event_jbtnbienbenidaActionPerformed

    private void jbtnsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsalidaActionPerformed
        // TODO add your handling code here:
      int opcion;
      opcion = JOptionPane.showConfirmDialog(null,"¿desea salir?", "salir",
              JOptionPane.YES_NO_OPTION);
      if(opcion == JOptionPane.YES_OPTION){
          System.exit(0);
      }
    }//GEN-LAST:event_jbtnsalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtconvertidos;
    private javax.swing.JButton jbtnbienbenida;
    private javax.swing.JButton jbtnsalida;
    // End of variables declaration//GEN-END:variables
}
